animationSystem.cameraSpring.use 1
animationSystem.cameraSpring.amplitude 0.02/0.02/0.05
animationSystem.cameraSpring.zoomDamping 2/2/2
animationSystem.cameraSpring.stiffness 60/60/60
animationSystem.cameraSpring.move 2/2/2
animationSystem.cameraSpring.look 1/1
animationSystem.cameraSpring.fire 0/0/60

rem *** Animations ***
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_0.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_1.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_2.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_3.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_4.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_5.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_6.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_7.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_8.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_9.baf
animationManager.looping 0
animationManager.length 1.66667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_1.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_2.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_3.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_4.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_5.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_6.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_7.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_8.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_9.baf
animationManager.looping 0
animationManager.noiceFreq 3
animationManager.noiceAmplitude 0.002
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_reload_1.baf
animationManager.length 7.29167
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_reload_2.baf
animationManager.length 7.29167
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_0.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_1.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_2.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_3.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_4.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_5.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_6.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_7.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_8.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_9.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_0.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_1.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_2.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_3.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_4.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_5.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_6.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_7.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_8.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_9.baf
animationManager.looping 0
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_0.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_1.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_2.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_3.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_4.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_5.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_6.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_7.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_8.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_9.baf
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8nanimationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8nanimationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8nanimationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf
animationManager.looping 0
animationManager.length 0.8
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_7.baf
animationManager.looping 0
animationManager.length 0.8
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_8.baf
animationManager.looping 0
animationManager.length 0.8
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_9.baf
animationManager.looping 0
animationManager.length 0.8
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_fire.baf
animationManager.looping 0
animationManager.length 0.583333
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_run.baf
animationManager.length 1.79167
animationSystem.createAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_stand.baf

rem *** Bundles ***
animationSystem.createBundle deploy
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy.baf

animationSystem.createBundle deploy_0
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_0.baf

animationSystem.createBundle deploy_1
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_1.baf

animationSystem.createBundle deploy_2
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_2.baf

animationSystem.createBundle deploy_3
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_3.baf

animationSystem.createBundle deploy_4
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_4.baf

animationSystem.createBundle deploy_5
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_5.baf

animationSystem.createBundle deploy_6
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_6.baf

animationSystem.createBundle deploy_7
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_7.baf

animationSystem.createBundle deploy_8
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_8.baf

animationSystem.createBundle deploy_9
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 1.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_deploy_9.baf

animationSystem.createBundle fire
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire.baf

animationSystem.createBundle fire_1
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_1.baf

animationSystem.createBundle fire_2
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_2.baf

animationSystem.createBundle fire_3
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_3.baf

animationSystem.createBundle fire_4
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_4.baf

animationSystem.createBundle fire_5
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_5.baf

animationSystem.createBundle fire_6
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_6.baf

animationSystem.createBundle fire_7
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_7.baf

animationSystem.createBundle fire_8
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_8.baf

animationSystem.createBundle fire_9
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_fire_9.baf

animationSystem.createBundle reload
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_reload_2.baf
animationBundle.addEvent effect:0
animationBundle.setEventStartTime effect:0 2.25

animationSystem.createBundle reload_0
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_reload_1.baf
animationBundle.addEvent effect:0
animationBundle.setEventStartTime effect:0 2.25

animationSystem.createBundle run
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run.baf

animationSystem.createBundle run_0
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_0.baf

animationSystem.createBundle run_1
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_1.baf

animationSystem.createBundle run_2
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_2.baf

animationSystem.createBundle run_3
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_3.baf

animationSystem.createBundle run_4
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_4.baf

animationSystem.createBundle run_5
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_5.baf

animationSystem.createBundle run_6
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_6.baf

animationSystem.createBundle run_7
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_7.baf

animationSystem.createBundle run_8
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_8.baf

animationSystem.createBundle run_9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_run_9.baf

animationSystem.createBundle sprint
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint.baf

animationSystem.createBundle sprint_0
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_0.baf

animationSystem.createBundle sprint_1
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_1.baf

animationSystem.createBundle sprint_2
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_2.baf

animationSystem.createBundle sprint_3
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_3.baf

animationSystem.createBundle sprint_4
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_4.baf

animationSystem.createBundle sprint_5
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_5.baf

animationSystem.createBundle sprint_6
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_6.baf

animationSystem.createBundle sprint_7
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_7.baf

animationSystem.createBundle sprint_8
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_8.baf

animationSystem.createBundle sprint_9
animationBundle.fadeInTime 0.9
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_sprint_9.baf

animationSystem.createBundle still
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand.baf

animationSystem.createBundle still_0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_0.baf

animationSystem.createBundle still_1
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_1.baf

animationSystem.createBundle still_2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_2.baf

animationSystem.createBundle still_3
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_3.baf

animationSystem.createBundle still_4
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_4.baf

animationSystem.createBundle still_5
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_5.baf

animationSystem.createBundle still_6
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_6.baf

animationSystem.createBundle still_7
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_7.baf

animationSystem.createBundle still_8
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_8.baf

animationSystem.createBundle still_9
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_stand_9.baf

animationSystem.createBundle zoom_fire
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0.5
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_fire.baf

animationSystem.createBundle zoom_run
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_run.baf

animationSystem.createBundle zoom_still
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_zoom_stand.baf

animationSystem.createBundle zoomTransition
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom.baf

animationSystem.createBundle zoomTransition_0
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_0.baf

animationSystem.createBundle zoomTransition_1
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_1.baf

animationSystem.createBundle zoomTransition_2
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_2.baf

animationSystem.createBundle zoomTransition_3
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_3.baf

animationSystem.createBundle zoomTransition_4
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_4.baf

animationSystem.createBundle zoomTransition_5
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_5.baf

animationSystem.createBundle zoomTransition_6
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_6.baf

animationSystem.createBundle zoomTransition_7
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_7.baf

animationSystem.createBundle zoomTransition_8
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_8.baf

animationSystem.createBundle zoomTransition_9
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/MG_xm22/Animations/1p/1p_FN_tozoom_9.baf


rem *** Triggers ***
animationSystem.createTrigger Trigger zoom_still
animationTrigger.addBundle zoom_still

animationSystem.createTrigger MovementTrigger zoom_move
animationTrigger.addBundle zoom_run
animationTrigger.valueHolder 1p_zoom_move

animationSystem.createTrigger MessageTrigger zoom_fire
animationTrigger.addBundle zoom_fire
animationTrigger.message 1

animationSystem.createTrigger Trigger zoom
animationTrigger.addChild zoom_still
animationTrigger.addChild zoom_move
animationTrigger.addChild zoom_fire

animationSystem.createTrigger Trigger still
animationTrigger.addBundle still

animationSystem.createTrigger MovementTrigger move
animationTrigger.addBundle run
animationTrigger.valueHolder 1p_move

animationSystem.createTrigger MovementTrigger sprint
animationTrigger.addBundle sprint
animationTrigger.valueHolder 1p_sprint

animationSystem.createTrigger MessageTrigger fire
animationTrigger.addBundle fire
animationTrigger.message 1

animationSystem.createTrigger MessageTrigger reload
animationTrigger.addBundle reload_0
animationTrigger.message 2

animationSystem.createTrigger Trigger normal
animationTrigger.fadeInTime 0.2
animationTrigger.addChild still
animationTrigger.addChild move
animationTrigger.addChild sprint
animationTrigger.addChild fire
animationTrigger.addChild reload

animationSystem.createTrigger SwitchMessageTrigger root
animationTrigger.addChild zoom
animationTrigger.addChild normal
animationTrigger.addBundle zoomTransition
animationTrigger.message 4

animationSystem.createTrigger Trigger startup
animationTrigger.addBundle deploy

animationSystem.createTrigger Trigger completeTree
animationTrigger.addChild root
animationTrigger.addChild startup

