AnimationSystem.createValueHolder 1p_move
AnimationValueHolder.values 0.25 4.2 10
AnimationSystem.createValueHolder 1p_sprint
AnimationValueHolder.values 5 6.3 100
AnimationSystem.createValueHolder 1p_turn
AnimationValueHolder.values -1 -3 -10
AnimationSystem.createValueHolder 1p_turnRight
AnimationValueHolder.values 1 3 10
AnimationSystem.createValueHolder 1p_zoom_move
AnimationValueHolder.values 0.25 0.9 10
AnimationSystem.createValueHolder 3p_climb
AnimationValueHolder.values 0 0.35 100
AnimationSystem.createValueHolder 3p_climb_skid
AnimationValueHolder.values -3 3 -1000
AnimationSystem.createValueHolder 3p_crouch_move
AnimationValueHolder.values 0.1 1.7 10
AnimationSystem.createValueHolder 3p_jump
AnimationValueHolder.values 0.25 2.5 8
AnimationSystem.createValueHolder 3p_jumpBackward
AnimationValueHolder.values -0.5 3.9 -100
AnimationSystem.createValueHolder 3p_jumpForward
AnimationValueHolder.values 0.5 3.9 100
AnimationSystem.createValueHolder 3p_jumpLeft
AnimationValueHolder.values -0.5 3.9 -100
AnimationSystem.createValueHolder 3p_jumpRight
AnimationValueHolder.values 0.5 3.9 100
AnimationSystem.createValueHolder 3p_jumpStill
AnimationValueHolder.values 0 0 0.5
AnimationSystem.createValueHolder 3p_prone_move
AnimationValueHolder.values 0.1 0.7 10
AnimationSystem.createValueHolder 3p_prone_turnLeft
AnimationValueHolder.values -0.01 1 -1000
AnimationSystem.createValueHolder 3p_prone_turnRight
AnimationValueHolder.values 0.01 1 1000
AnimationSystem.createValueHolder 3p_skydive_move
AnimationValueHolder.values 0.1 10 1000
AnimationSystem.createValueHolder 3p_skydive_speed
AnimationValueHolder.values -20 1 -1000
AnimationSystem.createValueHolder 3p_sprint
AnimationValueHolder.values 5 6.3 100
AnimationSystem.createValueHolder 3p_stand_run
AnimationValueHolder.values 0.1 3.9 5.8
AnimationValueHolder.stopOnMessage 4
AnimationSystem.createValueHolder 3p_stand_run_stop
AnimationValueHolder.values 20 1 10000
AnimationValueHolder.stopOnMessage 4
AnimationSystem.createValueHolder 3p_stand_run_stop_speed
AnimationValueHolder.values 3 1 100
AnimationValueHolder.stopOnMessage 4
AnimationSystem.createValueHolder 3p_stand_walk
AnimationValueHolder.values 0.1 1.5 2.0
AnimationValueHolder.passOnMessage 4
AnimationSystem.createValueHolder 3p_still
AnimationValueHolder.values 0 1 50
AnimationSystem.createValueHolder 3p_swimBackward
AnimationValueHolder.values -0.1 1.9 -2.1
AnimationSystem.createValueHolder 3p_swimForward
AnimationValueHolder.values 0.1 1.9 2.2
AnimationSystem.createValueHolder 3p_swimSprint
AnimationValueHolder.values 1.95 2.4 10
AnimationSystem.createValueHolder 3p_swimStill
AnimationValueHolder.values 0 0.01 0.1
AnimationSystem.createValueHolder 3p_turnLeft
AnimationValueHolder.values -0.05 1 -1000
AnimationSystem.createValueHolder 3p_turnRight
AnimationValueHolder.values 0.01 1 1000
